### ISSUE TITLE
Initial Migration Fails

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-dapp#11]
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: Exceeds block gas limit

**Comment by OR13** [comment]
Yeah, I got that a lot... I think its been resolved now.

**Comment by OR13** [comment]
See advanced branch

**Comment by eolszewski** [comment]
@OR13 still getting this... not sure what the problem is here...

**Comment by eolszewski** [comment]
```
dapp_1       | Using network 'development'.
dapp_1       | 
dapp_1       | Running migration: 1_initial_migration.js
testrpc_1    | eth_accounts
testrpc_1    | net_version
dapp_1       |   Deploying Migrations...
testrpc_1    | net_version
testrpc_1    | eth_sendTransaction
functions_1  | Server has started and listening on : 0.0.0.0:3001
dapp_1       |   ... undefined
dapp_1       | Error encountered, bailing. Network state unknown. Review successful transactions manually.
dapp_1       | Error: Error: Exceeds block gas limit
```

**Comment by eolszewski** [comment]
Solved by pinning truffle to beta version

**Comment by eolszewski** [comment]
8347c6ea0424863907da493caa46b1805532b1e6
